#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : gsm
Version  : 1.0.22
Release  : 4
URL      : https://www.quut.com/gsm/gsm-1.0.22.tar.gz
Source0  : https://www.quut.com/gsm/gsm-1.0.22.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : ISC
Requires: gsm-bin = %{version}-%{release}
Requires: gsm-lib = %{version}-%{release}
Requires: gsm-license = %{version}-%{release}
Requires: gsm-man = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-New-patch-generated-from-libgsm-1.0.10-14-diff.gz.patch
Patch2: 0002-Add-C-guard-to-gsm.h-Closes-202712.patch
Patch3: 0003-Change-errno-handling-to-fix-Hurd-Closes-164191-1641.patch
Patch4: 0004-Clean-up-comiler-warnings-Closes-226561.patch
Patch5: 0005-Correct-manual-page-markup.patch
Patch6: 0006-Fix-installation-destinations.patch

%description
GSM 06.10 13 kbit/s RPE/LTP speech compression available
--------------------------------------------------------

%package bin
Summary: bin components for the gsm package.
Group: Binaries
Requires: gsm-license = %{version}-%{release}

%description bin
bin components for the gsm package.


%package dev
Summary: dev components for the gsm package.
Group: Development
Requires: gsm-lib = %{version}-%{release}
Requires: gsm-bin = %{version}-%{release}
Provides: gsm-devel = %{version}-%{release}
Requires: gsm = %{version}-%{release}

%description dev
dev components for the gsm package.


%package lib
Summary: lib components for the gsm package.
Group: Libraries
Requires: gsm-license = %{version}-%{release}

%description lib
lib components for the gsm package.


%package license
Summary: license components for the gsm package.
Group: Default

%description license
license components for the gsm package.


%package man
Summary: man components for the gsm package.
Group: Default

%description man
man components for the gsm package.


%prep
%setup -q -n gsm-1.0-pl22
cd %{_builddir}/gsm-1.0-pl22
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
%patch -P 5 -p1
%patch -P 6 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689898125
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
make  CFLAGS+="-fPIC -Iinc -c"


%install
export SOURCE_DATE_EPOCH=1689898125
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gsm
cp %{_builddir}/gsm-1.0-pl22/COPYRIGHT %{buildroot}/usr/share/package-licenses/gsm/8f38b3e21abeebe41f1860f88a08219f1777e96e || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tcat
/usr/bin/toast
/usr/bin/untoast

%files dev
%defattr(-,root,root,-)
/usr/include/gsm.h
/usr/lib64/libgsm.so
/usr/share/man/man3/gsm.3
/usr/share/man/man3/gsm_explode.3
/usr/share/man/man3/gsm_option.3
/usr/share/man/man3/gsm_print.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgsm.so.1
/usr/lib64/libgsm.so.1.0.18

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gsm/8f38b3e21abeebe41f1860f88a08219f1777e96e

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/toast.1
